/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerWalletRouteImport } from './routes/seller.wallet'
import { Route as SellerVerificationRouteImport } from './routes/seller.verification'
import { Route as SellerSubscriptionsRouteImport } from './routes/seller.subscriptions'
import { Route as SellerStorefrontRouteImport } from './routes/seller.storefront'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerPromotionsRouteImport } from './routes/seller.promotions'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerOptimizeRouteImport } from './routes/seller.optimize'
import { Route as SellerNewProductRouteImport } from './routes/seller.new-product'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SUsernameRouteImport } from './routes/s.$username'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as DisputesOrderIdRouteImport } from './routes/disputes.$orderId'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminRiskRouteImport } from './routes/admin.risk'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminFxRouteImport } from './routes/admin.fx'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountSubscriptionsRouteImport } from './routes/account.subscriptions'
import { Route as AccountFollowingRouteImport } from './routes/account.following'
import { Route as AccountAffiliateRouteImport } from './routes/account.affiliate'
import { Route as SellerStockProductIdRouteImport } from './routes/seller.stock.$productId'
import { Route as ApiPublicImgIdRouteImport } from './routes/api/public/img.$id'
import { Route as ApiPublicCronFollowDigestRouteImport } from './routes/api/public/cron/follow-digest'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerWalletRoute = SellerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SellerRoute,
} as any)
const SellerVerificationRoute = SellerVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSubscriptionsRoute = SellerSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerStorefrontRoute = SellerStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPromotionsRoute = SellerPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOptimizeRoute = SellerOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNewProductRoute = SellerNewProductRouteImport.update({
  id: '/new-product',
  path: '/new-product',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const SUsernameRoute = SUsernameRouteImport.update({
  id: '/s/$username',
  path: '/s/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesOrderIdRoute = DisputesOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DisputesRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFxRoute = AdminFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSubscriptionsRoute = AccountSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFollowingRoute = AccountFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAffiliateRoute = AccountAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AccountRoute,
} as any)
const SellerStockProductIdRoute = SellerStockProductIdRouteImport.update({
  id: '/stock/$productId',
  path: '/stock/$productId',
  getParentRoute: () => SellerRoute,
} as any)
const ApiPublicImgIdRoute = ApiPublicImgIdRouteImport.update({
  id: '/api/public/img/$id',
  path: '/api/public/img/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFollowDigestRoute =
  ApiPublicCronFollowDigestRouteImport.update({
    id: '/api/public/cron/follow-digest',
    path: '/api/public/cron/follow-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/disputes/$orderId': typeof DisputesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/r/$code': typeof RCodeRoute
  '/s/$username': typeof SUsernameRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/new-product': typeof SellerNewProductRoute
  '/seller/optimize': typeof SellerOptimizeRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/seller/subscriptions': typeof SellerSubscriptionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/seller/stock/$productId': typeof SellerStockProductIdRoute
  '/api/public/cron/follow-digest': typeof ApiPublicCronFollowDigestRoute
  '/api/public/img/$id': typeof ApiPublicImgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/disputes/$orderId': typeof DisputesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/r/$code': typeof RCodeRoute
  '/s/$username': typeof SUsernameRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/new-product': typeof SellerNewProductRoute
  '/seller/optimize': typeof SellerOptimizeRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/seller/subscriptions': typeof SellerSubscriptionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/seller': typeof SellerIndexRoute
  '/seller/stock/$productId': typeof SellerStockProductIdRoute
  '/api/public/cron/follow-digest': typeof ApiPublicCronFollowDigestRoute
  '/api/public/img/$id': typeof ApiPublicImgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/disputes/$orderId': typeof DisputesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/r/$code': typeof RCodeRoute
  '/s/$username': typeof SUsernameRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/new-product': typeof SellerNewProductRoute
  '/seller/optimize': typeof SellerOptimizeRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/seller/subscriptions': typeof SellerSubscriptionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/seller/stock/$productId': typeof SellerStockProductIdRoute
  '/api/public/cron/follow-digest': typeof ApiPublicCronFollowDigestRoute
  '/api/public/img/$id': typeof ApiPublicImgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/disputes'
    | '/favorites'
    | '/menu'
    | '/notifications'
    | '/robots.txt'
    | '/sell'
    | '/seller'
    | '/sitemap.xml'
    | '/wallet'
    | '/account/affiliate'
    | '/account/following'
    | '/account/subscriptions'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/fx'
    | '/admin/items'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/risk'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/disputes/$orderId'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/pay/$orderId'
    | '/r/$code'
    | '/s/$username'
    | '/seller/analytics'
    | '/seller/new-product'
    | '/seller/optimize'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/reviews'
    | '/seller/storefront'
    | '/seller/subscriptions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/admin/'
    | '/orders/'
    | '/seller/'
    | '/seller/stock/$productId'
    | '/api/public/cron/follow-digest'
    | '/api/public/img/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/disputes'
    | '/favorites'
    | '/menu'
    | '/notifications'
    | '/robots.txt'
    | '/sell'
    | '/sitemap.xml'
    | '/wallet'
    | '/account/affiliate'
    | '/account/following'
    | '/account/subscriptions'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/fx'
    | '/admin/items'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/risk'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/disputes/$orderId'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/pay/$orderId'
    | '/r/$code'
    | '/s/$username'
    | '/seller/analytics'
    | '/seller/new-product'
    | '/seller/optimize'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/reviews'
    | '/seller/storefront'
    | '/seller/subscriptions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/admin'
    | '/orders'
    | '/seller'
    | '/seller/stock/$productId'
    | '/api/public/cron/follow-digest'
    | '/api/public/img/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/disputes'
    | '/favorites'
    | '/menu'
    | '/notifications'
    | '/robots.txt'
    | '/sell'
    | '/seller'
    | '/sitemap.xml'
    | '/wallet'
    | '/account/affiliate'
    | '/account/following'
    | '/account/subscriptions'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/fx'
    | '/admin/items'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/risk'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/disputes/$orderId'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/pay/$orderId'
    | '/r/$code'
    | '/s/$username'
    | '/seller/analytics'
    | '/seller/new-product'
    | '/seller/optimize'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/reviews'
    | '/seller/storefront'
    | '/seller/subscriptions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/admin/'
    | '/orders/'
    | '/seller/'
    | '/seller/stock/$productId'
    | '/api/public/cron/follow-digest'
    | '/api/public/img/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ChatRoute: typeof ChatRoute
  DisputesRoute: typeof DisputesRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  MenuRoute: typeof MenuRoute
  NotificationsRoute: typeof NotificationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WalletRoute: typeof WalletRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PSlugRoute: typeof PSlugRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  RCodeRoute: typeof RCodeRoute
  SUsernameRoute: typeof SUsernameRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicCronFollowDigestRoute: typeof ApiPublicCronFollowDigestRoute
  ApiPublicImgIdRoute: typeof ApiPublicImgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/wallet': {
      id: '/seller/wallet'
      path: '/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof SellerWalletRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/verification': {
      id: '/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof SellerVerificationRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/subscriptions': {
      id: '/seller/subscriptions'
      path: '/subscriptions'
      fullPath: '/seller/subscriptions'
      preLoaderRoute: typeof SellerSubscriptionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/storefront': {
      id: '/seller/storefront'
      path: '/storefront'
      fullPath: '/seller/storefront'
      preLoaderRoute: typeof SellerStorefrontRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/promotions': {
      id: '/seller/promotions'
      path: '/promotions'
      fullPath: '/seller/promotions'
      preLoaderRoute: typeof SellerPromotionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/optimize': {
      id: '/seller/optimize'
      path: '/optimize'
      fullPath: '/seller/optimize'
      preLoaderRoute: typeof SellerOptimizeRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/new-product': {
      id: '/seller/new-product'
      path: '/new-product'
      fullPath: '/seller/new-product'
      preLoaderRoute: typeof SellerNewProductRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/s/$username': {
      id: '/s/$username'
      path: '/s/$username'
      fullPath: '/s/$username'
      preLoaderRoute: typeof SUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$orderId': {
      id: '/disputes/$orderId'
      path: '/$orderId'
      fullPath: '/disputes/$orderId'
      preLoaderRoute: typeof DisputesOrderIdRouteImport
      parentRoute: typeof DisputesRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fx': {
      id: '/admin/fx'
      path: '/fx'
      fullPath: '/admin/fx'
      preLoaderRoute: typeof AdminFxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/subscriptions': {
      id: '/account/subscriptions'
      path: '/subscriptions'
      fullPath: '/account/subscriptions'
      preLoaderRoute: typeof AccountSubscriptionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/following': {
      id: '/account/following'
      path: '/following'
      fullPath: '/account/following'
      preLoaderRoute: typeof AccountFollowingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/affiliate': {
      id: '/account/affiliate'
      path: '/affiliate'
      fullPath: '/account/affiliate'
      preLoaderRoute: typeof AccountAffiliateRouteImport
      parentRoute: typeof AccountRoute
    }
    '/seller/stock/$productId': {
      id: '/seller/stock/$productId'
      path: '/stock/$productId'
      fullPath: '/seller/stock/$productId'
      preLoaderRoute: typeof SellerStockProductIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/api/public/img/$id': {
      id: '/api/public/img/$id'
      path: '/api/public/img/$id'
      fullPath: '/api/public/img/$id'
      preLoaderRoute: typeof ApiPublicImgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/follow-digest': {
      id: '/api/public/cron/follow-digest'
      path: '/api/public/cron/follow-digest'
      fullPath: '/api/public/cron/follow-digest'
      preLoaderRoute: typeof ApiPublicCronFollowDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAffiliateRoute: typeof AccountAffiliateRoute
  AccountFollowingRoute: typeof AccountFollowingRoute
  AccountSubscriptionsRoute: typeof AccountSubscriptionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAffiliateRoute: AccountAffiliateRoute,
  AccountFollowingRoute: AccountFollowingRoute,
  AccountSubscriptionsRoute: AccountSubscriptionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFxRoute: typeof AdminFxRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFxRoute: AdminFxRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DisputesRouteChildren {
  DisputesOrderIdRoute: typeof DisputesOrderIdRoute
}

const DisputesRouteChildren: DisputesRouteChildren = {
  DisputesOrderIdRoute: DisputesOrderIdRoute,
}

const DisputesRouteWithChildren = DisputesRoute._addFileChildren(
  DisputesRouteChildren,
)

interface SellerRouteChildren {
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerNewProductRoute: typeof SellerNewProductRoute
  SellerOptimizeRoute: typeof SellerOptimizeRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerPromotionsRoute: typeof SellerPromotionsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerStorefrontRoute: typeof SellerStorefrontRoute
  SellerSubscriptionsRoute: typeof SellerSubscriptionsRoute
  SellerVerificationRoute: typeof SellerVerificationRoute
  SellerWalletRoute: typeof SellerWalletRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerStockProductIdRoute: typeof SellerStockProductIdRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerNewProductRoute: SellerNewProductRoute,
  SellerOptimizeRoute: SellerOptimizeRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerPromotionsRoute: SellerPromotionsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerStorefrontRoute: SellerStorefrontRoute,
  SellerSubscriptionsRoute: SellerSubscriptionsRoute,
  SellerVerificationRoute: SellerVerificationRoute,
  SellerWalletRoute: SellerWalletRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerStockProductIdRoute: SellerStockProductIdRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ChatRoute: ChatRoute,
  DisputesRoute: DisputesRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  MenuRoute: MenuRoute,
  NotificationsRoute: NotificationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WalletRoute: WalletRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PSlugRoute: PSlugRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  RCodeRoute: RCodeRoute,
  SUsernameRoute: SUsernameRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicCronFollowDigestRoute: ApiPublicCronFollowDigestRoute,
  ApiPublicImgIdRoute: ApiPublicImgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
